export const ASSETS: [string, string, string, string, number, number][] = [
    [
        'Hyper Solana',
        'HYSOL',
        'Hyper coin for Solana!',
        'https://arweave.net/ArreGQ6DYdIPGs_KiwVXE7AMVclLliICTlls6Ff8DbY',
        9,
        8000,
    ],
    [
        'Pt Solana',
        'PTSOL',
        'Peter coin for Solana!',
        'https://arweave.net/ZlxqEw-BVEO7LKLWE7uKJoCxC67w-0zaO9ydX-m6y7A',
        9,
        1000,
    ],
    [
        'Love Solana',
        'LOVSOL',
        'Love coin for Solana!',
        'https://arweave.net/MvWxgCu231-0IrE3FWoaAYoFaD1MgWKOqDjCv5v6LEA',
        3,
        2000,
    ],
    [
        'Elastic Solana',
        'ELSOL',
        'Elastic coin for Solana!',
        'https://arweave.net/2wCk8mVH8KyqwbYLlxae9kBBKb4jTRPeiXVrqUTvjUE',
        9,
        5000,
    ],
    [
        'Gold Solana',
        'GSOL',
        'Gold coin for Solana!',
        'https://arweave.net/46B9y63MXlLnprZLvrRjS_50yecOydiLbxTbieAREBk',
        6,
        5000,
    ],
    [
        'Lucky Solana',
        'LUCKSOL',
        'Lucky coin for Solana!',
        'https://arweave.net/RT9sF6ENI__DQGYD74H4SdncsjLyeO1Rm3dRQ1T1Tz0',
        3,
        500,
    ],
    [
        'Gunpowder Solana',
        'GUNPSOL',
        'Gunpowder coin for Solana!',
        'https://arweave.net/eLqSxbbW7ATsQioluBZt9KG0YnU0jRoR_46g0EJU75Q',
        9,
        6000,
    ],
    [
        'Musket Solana',
        'MUSKSOL',
        'A musket coin for Solana!',
        'https://arweave.net/tKdMfImOkHEqo8xWulIv92MybdpkbnWjDJmazj3lTpU',
        3,
        600,
    ],
    [
        'Rum Solana',
        'RUMSOL',
        'Rum coin for Solana',
        'https://arweave.net/NJGvUP2EuK-LJ7QV6qRifcGC8ao2Vd9WSW2GjiGSpVw',
        6,
        1000,
    ],
    [
        'Telescope Solana',
        'TELESOL',
        'Telescope coin for Solana!',
        'https://arweave.net/NmBFKuCWk4yfAB4a6EGwXlWM92q5B9nBZMlRhpVA4y4',
        3,
        200,
    ],
    [
        'Treasure Map Solana',
        'TMAP',
        'Treasure Map coin for Solana!',
        'https://arweave.net/_cM90jcVdRRYt-OA8xIV--gZCAOpe18BCLvV2TVW7Fc',
        3,
        100,
    ],
]